import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{supabase}from'./supabase';
import{UserRound,ShieldCheck,ChevronRight,LogOut,PackageCheck,TrendingUp,FileSpreadsheet,CheckCircle2,Upload,CalendarDays,Target,AlertTriangle}from'lucide-react';
import*as XLSX from'xlsx';
import'./styles.css';
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:2}).format(Number(n||0));
const fechaAR=f=>{const [y,m,d]=String(f||'').split('-');return d&&m&&y?`${d}/${m}/${y}`:f};
const nombreMes=m=>['','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][m]||m;
const estadoColor=p=>p>130?{color:'#7030A0',texto:'Sobresaliente'}:p>=95?{color:'#00B050',texto:'Objetivo'}:p>=85?{color:'#FFF200',texto:'Atención',dark:true}:{color:'#FF0000',texto:'Bajo objetivo'};
const dur=s=>{const m=Math.round(Number(s||0)/60),h=Math.floor(m/60);return h?`${h} h ${String(m%60).padStart(2,'0')} min`:`${m} min`};
const normal=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]+/g,' ').trim().toUpperCase();
function App(){const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(!session){setProfile(null);return}supabase.from('perfiles').select('*,empleados(*)').eq('auth_user_id',session.user.id).single().then(({data})=>setProfile(data))},[session]);if(loading)return <Center text="Cargando..."/>;if(!session)return <Login/>;if(!profile)return <Center text="Preparando perfil..."/>;return profile.rol==='administrador'?<Admin profile={profile}/>:<Personal profile={profile}/>}
function Center({text}){return <div className="center"><b>{text}</b></div>}
function Login(){const[role,setRole]=useState('personal'),[user,setUser]=useState('29027047'),[pass,setPass]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function go(){setBusy(true);setErr('');const email=role==='personal'?`${user.trim()}@personal.local`:user.trim();const{error}=await supabase.auth.signInWithPassword({email,password:pass});if(error)setErr('Usuario o contraseña incorrectos.');setBusy(false)}return <div className="login"><section className="hero"><small>CD MERCADO CENTRAL</small><h1>Mi productividad,<br/><span>día a día.</span></h1><p>Clasificación manual, picking y control de errores en un solo lugar.</p></section><section className="form"><div className="box"><small>BIENVENIDO</small><h2>Ingresar</h2><div className="roles"><button className={role==='personal'?'active':''} onClick={()=>{setRole('personal');setUser('29027047')}}><UserRound/>Personal</button><button className={role==='admin'?'active':''} onClick={()=>{setRole('admin');setUser('')}}><ShieldCheck/>Administrador</button></div><label>{role==='personal'?'Número de legajo':'Correo del administrador'}</label><input value={user} onChange={e=>setUser(e.target.value)}/><label>Contraseña</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/>{err&&<div className="error">{err}</div>}<button className="primary" onClick={go} disabled={busy}>{busy?'Ingresando...':<>Ingresar <ChevronRight/></>}</button></div></section></div>}
function Header({profile}){return <header><div><b>Mi Productividad</b><small>CD Mercado Central · DPO</small></div><div className="headright"><span>{profile.rol==='administrador'?'Administrador':profile.empleados?.apellido_nombre}</span><button onClick={()=>supabase.auth.signOut()}><LogOut/></button></div></header>}
function Personal({profile}){const[mod,setMod]=useState('manual'),[periods,setPeriods]=useState([]),[period,setPeriod]=useState('');useEffect(()=>{supabase.from('periodos').select('*').eq('publicado',true).order('anio',{ascending:false}).order('mes',{ascending:false}).then(({data})=>{setPeriods(data||[]);if(data?.[0])setPeriod(data[0].id)})},[]);return <><Header profile={profile}/><main><div className="title"><small>PANEL PERSONAL</small><h1>Hola, {profile.empleados?.apellido_nombre?.split(',')[0]}</h1><p>Datos vinculados por persona y actividad</p><div className="period-box"><CalendarDays/><div><span>PERÍODO CONSULTADO</span><select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.length?periods.map(p=><option key={p.id} value={p.id}>{nombreMes(p.mes)} {p.anio}</option>):<option>Sin períodos publicados</option>}</select></div></div></div><nav>{[['manual',PackageCheck,'Clasificación manual'],['picking',TrendingUp,'Picking'],['gatera',FileSpreadsheet,'Errores en gatera'],['voice',ShieldCheck,'Errores Voice Picking']].map(([id,I,t])=><button key={id} className={mod===id?'sel':''} onClick={()=>setMod(id)}><I/>{t}</button>)}</nav>{period?<Modulo tipo={mod} periodo={period} profile={profile}/>:<Empty text="No hay períodos publicados todavía."/>}</main></>}
function Modulo({tipo,periodo,profile}){const map={manual:'clasificacion_manual',picking:'picking',gatera:'errores_gatera',voice:'errores_voice'},[rows,setRows]=useState(null);useEffect(()=>{setRows(null);supabase.from(map[tipo]).select('*').eq('periodo_id',periodo).order('fecha',{ascending:false}).then(({data})=>setRows(data||[]))},[tipo,periodo]);if(rows===null)return <Center text="Cargando información..."/>;if(!rows.length)return <Empty text="Sin actividad registrada en este período."/>;if(tipo==='manual')return <Table title="Clasificación manual" heads={['Fecha','Objetivo','Real','Diferencia','Cumplimiento']} rows={rows.map(r=>[fechaAR(r.fecha),fmt(r.objetivo),fmt(r.real),fmt(r.diferencia),`${fmt(Number(r.cumplimiento)*100)}%`])}/>;if(tipo==='picking')return <PickingVisual rows={rows} profile={profile}/>;if(tipo==='gatera')return <Table title="Errores detectados en gatera" heads={['Fecha','Cancha','Motivo','Cantidad','SKU','Comentario']} rows={rows.map(r=>[fechaAR(r.fecha),r.cancha,r.motivo,fmt(r.cantidad),r.sku,r.comentario])}/>;return <Table title="Errores Voice Picking" heads={['Fecha','Cancha','Paleta','Bultos','Motivo','Errores']} rows={rows.map(r=>[fechaAR(r.fecha),r.cancha,r.numero_paleta,fmt(r.bultos),r.motivo||'Sin novedad',fmt(r.total_errores)])}/>}
function Cumplimiento({value}){const e=estadoColor(value);return <span className="cumple" style={{background:e.color,color:e.dark?'#403500':'#fff'}}>{value.toFixed(1)}%</span>}
function Kpi({icon:Icon,label,value,sub,color}){return <div className="kpi" style={{borderColor:color}}><div className="kpi-icon" style={{color,background:`${color}18`}}><Icon/></div><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function BarraTarget({productividad,target}){const max=Math.max(productividad,target)*1.15,e=estadoColor(productividad/target*100);return <div className="target-wrap"><div className="target-labels"><span>Target {fmt(target)}</span><span>Productividad {fmt(productividad)}</span></div><div className="target-track"><i style={{left:`${Math.min(98,target/max*100)}%`}}/><em style={{width:`${Math.min(100,productividad/max*100)}%`,background:e.color}}/></div></div>}
function PickingVisual({rows,profile}){const dias=useMemo(()=>{const g={};rows.forEach(r=>{if(!g[r.fecha])g[r.fecha]={fecha:r.fecha,packs:0,pallets:0,segundos:0,targetPeso:0,items:[]};const d=g[r.fecha];d.packs+=Number(r.packs||0);d.pallets+=Number(r.pallets||0);d.segundos+=Number(r.duracion_segundos||0);d.targetPeso+=Number(r.target||0)*Number(r.duracion_segundos||0);d.items.push(r)});return Object.values(g).map(d=>({...d,productividad:d.segundos?d.packs/(d.segundos/3600):0,target:d.segundos?d.targetPeso/d.segundos:0})).sort((a,b)=>b.fecha.localeCompare(a.fecha))},[rows]);const u=dias[0],cum=u.target?u.productividad/u.target*100:0,e=estadoColor(cum);return <><div className="module-head"><h2>Picking</h2><p>{profile.empleados?.apellido_nombre} · Turno {profile.empleados?.turno} · Varias canchas</p></div><div className="kpi-grid"><Kpi icon={TrendingUp} label="BULTOS POR HORA" value={fmt(u.productividad)} sub={`Consolidado del ${fechaAR(u.fecha).slice(0,5)}`} color="#006600"/><Kpi icon={Target} label="TARGET PONDERADO" value={fmt(u.target)} sub="Según el tiempo en cada cancha" color="#FFC000"/><Kpi icon={CheckCircle2} label="CUMPLIMIENTO" value={`${cum.toFixed(1)}%`} sub={e.texto} color={e.color}/></div><section className="daily panel"><h3>Resultado día por día</h3><p>Total diario y detalle de cada cancha</p>{dias.map(d=>{const dc=d.target?d.productividad/d.target*100:0;return <article className="day" key={d.fecha}><div className="day-head"><div><b>{fechaAR(d.fecha)}</b><small>Total del día: {fmt(d.packs)} packs · {fmt(d.pallets)} pallets · {dur(d.segundos)}</small></div><div><strong>{fmt(d.productividad)} bultos/h</strong><Cumplimiento value={dc}/></div></div>{d.items.map(r=>{const c=Number(r.target)?Number(r.productividad)/Number(r.target)*100:0;return <div className="activity" key={r.id}><div className="activity-main"><div><b className="court">{r.cancha}</b><small>{fmt(r.packs)} packs · {fmt(r.pallets)} pallets · {dur(r.duracion_segundos)}</small></div><div className="activity-result"><strong>{fmt(r.productividad)} bultos/h</strong><span>Target {fmt(r.target)}</span><Cumplimiento value={c}/></div></div><BarraTarget productividad={Number(r.productividad)} target={Number(r.target)}/></div>})}</article>})}</section><section className="panel detail"><h3>Detalle por actividad</h3><div className="scroll"><table><thead><tr>{['Fecha','Cancha','Packs','Pallets','Duración','Bultos/hora','Target','Cumplimiento'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{fechaAR(r.fecha)}</b></td><td><b>{r.cancha}</b></td><td>{fmt(r.packs)}</td><td>{fmt(r.pallets)}</td><td>{dur(r.duracion_segundos)}</td><td><b>{fmt(r.productividad)}</b></td><td>{fmt(r.target)}</td><td><Cumplimiento value={Number(r.target)?Number(r.productividad)/Number(r.target)*100:0}/></td></tr>)}</tbody></table></div></section></>}
function Empty({text}){return <div className="empty"><CheckCircle2/><h3>{text}</h3></div>}
function Table({title,heads,rows}){return <section className="panel"><h2>{title}</h2><div className="scroll"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??''}</td>)}</tr>)}</tbody></table></div></section>}
function excelFecha(v){if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null}const t=String(v||'').trim(),m=t.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m)return `${m[3].length===2?'20'+m[3]:m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;return null}
function segundos(v){if(v==null||v==='')return null;if(typeof v==='number')return Math.round(v<2?v*86400:v);const m=String(v).match(/^(\d+):(\d+)(?::(\d+))?/);return m?(+m[1]*3600)+(+m[2]*60)+ +(m[3]||0):null}
function hora(v){if(v==null||v==='')return null;if(typeof v==='number')return XLSX.SSF.format('hh:mm:ss',v);return String(v).slice(0,8)}
async function insertarLotes(tabla,filas){for(let i=0;i<filas.length;i+=250){const{error}=await supabase.from(tabla).insert(filas.slice(i,i+250));if(error)throw error}}
function Admin({profile}){
 const[type,setType]=useState('picking'),[year,setYear]=useState(2026),[month,setMonth]=useState(9),[file,setFile]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null);
 async function inspect(){
  if(!file)return setMsg('Seleccioná un archivo Excel.');setBusy(true);setMsg('Procesando el archivo. Puede demorar unos segundos...');setReview(null);await new Promise(r=>setTimeout(r,80));
  try{
   if(type!=='picking')throw new Error('La publicación real se habilitó primero para Picking. Los otros módulos se habilitan después de esta prueba.');
   const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellStyles:false,cellNF:false,cellHTML:false});const ws=wb.Sheets['Bajada General'];if(!ws)throw new Error('No se encontró la hoja Bajada General.');
   const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true});const hi=matrix.findIndex(r=>r.some(c=>normal(c)==='FECHA')&&r.some(c=>normal(c)==='OPERADOR')&&r.some(c=>['PACKS','BULTOS'].includes(normal(c))));if(hi<0)throw new Error('No se encontró la fila de encabezados de Picking.');
   const headers=matrix[hi].map(normal),ix=(...names)=>headers.findIndex(h=>names.map(normal).includes(h));const iFecha=ix('Fecha'),iTurno=ix('Turno'),iCancha=ix('Túnel','Cancha'),iOper=ix('Operador'),iPacks=ix('Packs','Bultos'),iPallets=ix('Pallets'),iInicio=ix('Inicio'),iFin=ix('Fin'),iDur=ix('Duración total'),iNeto=ix('~Tiempo neto trabajado','Tiempo neto trabajado'),iSin=ix('Tiempo no piqueando','Tiempo sin picking'),iProd=ix('Bultos/hora II','Packs/hora','Bultos/hora'),iTarget=headers.lastIndexOf('TARGET'),iDes=ix('Desvio','Desvío'),iColor=ix('Num/Color');
   const{data:emps,error}=await supabase.from('empleados').select('id,apellido_nombre,nombre_normalizado,activo');if(error)throw error;const{data:variantes,error:errorVariantes}=await supabase.from('variantes_nombres').select('empleado_id,variante_normalizada,activa');if(errorVariantes)throw errorVariantes;const byName=new Map((emps||[]).map(e=>[normal(e.nombre_normalizado||e.apellido_nombre),e]));const byId=new Map((emps||[]).map(e=>[e.id,e]));(variantes||[]).filter(v=>v.activa).forEach(v=>{const empleado=byId.get(v.empleado_id);if(empleado)byName.set(normal(v.variante_normalizada),empleado)});
   const valid=[],unknown=new Map(),seen=new Set();let discarded=0,duplicates=0;
   for(const r of matrix.slice(hi+1)){const fecha=excelFecha(r[iFecha]),cancha=String(r[iCancha]||'').trim().toUpperCase(),nombre=String(r[iOper]||'').trim(),packs=Number(r[iPacks]||0),pallets=Number(r[iPallets]||0);if(!fecha||!nombre||!/^C[1-6]$/.test(cancha)||packs<=0){discarded++;continue}const[y,m]=fecha.split('-').map(Number);if(y!==year||m!==month){discarded++;continue}const emp=byName.get(normal(nombre));if(!emp){unknown.set(normal(nombre),nombre);continue}const inicio=hora(r[iInicio]),fin=hora(r[iFin]),key=[emp.id,fecha,cancha,inicio,fin,packs,pallets].join('|');if(seen.has(key)){duplicates++;continue}seen.add(key);valid.push({empleado_id:emp.id,fecha,turno:String(r[iTurno]||''),cancha,packs,pallets,inicio,fin,duracion_segundos:segundos(r[iDur]),tiempo_neto_segundos:segundos(r[iNeto]),tiempo_sin_picking_segundos:segundos(r[iSin]),productividad:Number(r[iProd]||0),target:Number(r[iTarget]||0),desvio:Number(r[iDes]||0),num_color:Number(r[iColor]||0),datos_originales:{operador:nombre}})}
   setReview({valid,unknown:[...unknown.values()],discarded,duplicates,read:matrix.length-hi-1});setMsg('Vista previa terminada. Revisá los resultados antes de publicar.');
  }catch(e){setMsg(`No se pudo revisar: ${e.message}`)}finally{setBusy(false)}
 }
 async function publish(){if(!review?.valid.length)return;setBusy(true);setMsg('Publicando y reemplazando la versión anterior...');try{let{data:period,error}=await supabase.from('periodos').select('*').eq('anio',year).eq('mes',month).maybeSingle();if(error)throw error;if(!period){const r=await supabase.from('periodos').insert({anio:year,mes:month,publicado:false}).select().single();if(r.error)throw r.error;period=r.data}const ir=await supabase.from('importaciones').insert({periodo_id:period.id,tipo_archivo:'picking',nombre_archivo:file.name,hoja_origen:'Bajada General',registros_encontrados:review.read,registros_aceptados:review.valid.length,registros_rechazados:review.unknown.length+review.discarded,registros_duplicados:review.duplicates,estado:'procesando',cargado_por:profile.id}).select().single();if(ir.error)throw ir.error;const del=await supabase.from('picking').delete().eq('periodo_id',period.id);if(del.error)throw del.error;await insertarLotes('picking',review.valid.map(x=>({...x,periodo_id:period.id,importacion_id:ir.data.id})));await supabase.from('importaciones').update({estado:'publicado',publicado_en:new Date().toISOString()}).eq('id',ir.data.id);const up=await supabase.from('periodos').update({publicado:true,publicado_en:new Date().toISOString(),publicado_por:profile.id}).eq('id',period.id);if(up.error)throw up.error;setReview(null);setFile(null);setMsg(`Publicado: ${review.valid.length} registros. Picking ${String(month).padStart(2,'0')}/${year} fue reemplazado sin duplicar.`)}catch(e){setMsg(`No se publicó. La versión anterior se conserva. Detalle: ${e.message}`)}finally{setBusy(false)}}
 return <><Header profile={profile}/><main><div className="title"><small>PANEL ADMINISTRADOR</small><h1>Carga mensual</h1><p>La última carga válida reemplaza el mismo módulo, mes y año.</p></div><section className="panel admin"><label>Tipo de archivo</label><select value={type} onChange={e=>{setType(e.target.value);setFile(null);setReview(null);setMsg('')}}><option value="manual">Clasificación manual</option><option value="picking">Picking</option><option value="gatera">Errores en gatera</option><option value="voice">Errores Voice Picking</option></select><div className="twocol"><div><label>Mes</label><input type="number" min="1" max="12" value={month} onChange={e=>setMonth(+e.target.value)}/></div><div><label>Año</label><input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></div></div><label className="upload"><Upload/>Seleccionar Excel<input type="file" accept=".xlsx,.xls" onChange={e=>{setFile(e.target.files[0]);setReview(null);setMsg('')}}/></label>{file&&<p><b>{file.name}</b></p>}<button className="primary" onClick={inspect} disabled={busy}>{busy?'Procesando...':'Revisar archivo'}</button>{review&&<div className="notice"><div><b>Vista previa de Picking</b><p>Filas leídas: {review.read}</p><p>Registros válidos: {review.valid.length}</p><p>Operarios no reconocidos: {review.unknown.length}</p><p>Duplicados internos: {review.duplicates}</p><p>Filas descartadas: {review.discarded}</p>{review.unknown.length>0&&<p className="note">Pendientes: {review.unknown.slice(0,8).join(', ')}</p>}<button className="primary" onClick={publish} disabled={busy}>Reemplazar y publicar</button></div></div>}{msg&&<div className="notice"><AlertTriangle/>{msg}</div>}<p className="note">Por seguridad, la publicación real está habilitada primero para Picking.</p></section></main></>
}
createRoot(document.getElementById('root')).render(<App/>);
